spring:
  banner:
    location:
      'classpath:banner.txt'
  application:
    name : collectoro-backend
  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username : ${db.username}
    password : ${db.password}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 5
      idleTimeout: 30000
      poolName: collectoro-connection-pooling
      maxLifetime: 2000000
      connectionTimeout: 60000
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: boros.gergo@hotmail.com
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp-mail.outlook.com
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : create     # Hibernate ddl auto (create, create-drop, validate, update)
    generate-ddl: true

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    hu.bme.aut.dzsungelharcosok: INFO
  file:
    path: ./src/main/resources/logs/
    name: ${logging.file.path}collectoro-backend.log
#============================================================================
# DATABASE
#============================================================================
db:
  name : collectoro
  host : localhost
  port : 5432
  username : collectoro
  password : collectoro
  auto-reconnect : true
  ssl : false

#server:
#  ssl:
#    key-store-password: collectoro
#    key-store-type: PKCS12
#    key-store: src/main/resources/keystore.p12
#    enabled: 'true'
#    key-alias: collectoro
